FROM ubuntu:20.04
MAINTAINER Ai Okada <aokada@ncc.go.jp> 

RUN apt-get update && apt-get install -y --no-install-recommends \
    bzip2 \
    cpio \
    g++ \
    gcc \
    git \
    libbz2-dev \
    libcurl4-openssl-dev \
    liblzma-dev \
    libssl-dev \
    locales \
    make \
    patch \
    python3 \
    python3-pip \
    time \
    unzip \
    wget \
    zlib1g-dev

RUN wget -q https://github.com/samtools/htslib/releases/download/1.14/htslib-1.14.tar.bz2 && \
    tar jxvf htslib-1.14.tar.bz2 && \
    cd htslib-1.14 && \
    ./configure && \
    make && \
    make install 

RUN wget -q https://github.com/lh3/bwa/releases/download/v0.7.17/bwa-0.7.17.tar.bz2 && \
    tar jxvf bwa-0.7.17.tar.bz2 && \
    cd bwa-0.7.17 && \
    make 

ENV PATH /bwa-0.7.17:$PATH

RUN git clone https://github.com/lh3/fermi-lite && \
    cd fermi-lite && make

ENV PATH /fermi-lite:$PATH

# h5py is required by RepeatMasker
RUN pip3 install --upgrade setuptools && \
    pip3 install annot_utils==0.3.1 && \
    pip3 install pysam==0.16.0.1 && \
    pip3 install numpy==1.19.5 && \
    pip3 install scipy==1.5.4 && \
    pip3 install statistics==1.0.3.5 && \
    pip3 install parasail==1.2.4 && \
    pip3 install h5py

#RUN git clone https://github.com/mbreese/swalign.git && \
#    cd swalign && \
#    pip3 install . 

# required by parasail
RUN wget -q https://github.com/mengyao/Complete-Striped-Smith-Waterman-Library/archive/v1.1.tar.gz && \
    tar zxvf v1.1.tar.gz && \
    cd Complete-Striped-Smith-Waterman-Library-1.1/src && \
    gcc -Wall -O3 -pipe -fPIC -shared -rdynamic -o libssw.so ssw.c ssw.h

ENV LD_LIBRARY_PATH /Complete-Striped-Smith-Waterman-Library-1.1/src:$LD_LIBRARY_PATH

# RepeatMasker
RUN wget -q https://www.repeatmasker.org/RepeatMasker/RepeatMasker-4.1.2-p1.tar.gz && \
    tar zxvf RepeatMasker-4.1.2-p1.tar.gz && \
    mv RepeatMasker /usr/local/

ENV PATH /usr/local/RepeatMasker:$PATH

RUN wget -q https://github.com/Benson-Genomics-Lab/TRF/archive/refs/tags/v4.09.1.tar.gz && \
    tar zxvf v4.09.1.tar.gz && \
    cd TRF-4.09.1/ && \
    ./configure && \
    make && make install

#RUN wget http://www.repeatmasker.org/rmblast-2.11.0+-x64-linux.tar.gz && \
#    tar zxvf rmblast-2.11.0+-x64-linux.tar.gz && \
#    mv rmblast-2.11.0/bin/* /usr/local/bin/

RUN wget -q ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.11.0/ncbi-blast-2.11.0+-src.tar.gz && \
    tar xzvf ncbi-blast-2.11.0+-src.tar.gz && \
    cd ncbi-blast-2.11.0+-src/ && \
    wget -q http://www.repeatmasker.org/isb-2.11.0+-rmblast.patch.gz && \
    gunzip isb-2.11.0+-rmblast.patch.gz && \
    sed -i "s#https://www.repeatmasker.org/rmblast/stat#https://localhost/#" isb-2.11.0+-rmblast.patch && \
    patch -p1 < isb-2.11.0+-rmblast.patch && \
    cd c++/ && \
    ./configure  --with-mt --without-debug --without-krb5 --without-openssl --with-projects=scripts/projects/rmblastn/project.lst --prefix=/usr/local/rmblast-2.11.0 && \
    make -j "$(nproc)" && \
    make install

RUN cd /usr/local/RepeatMasker && \
    perl ./configure \
        -trf_prgm /usr/local/bin/trf \
        -rmblast_dir /usr/local/rmblast-2.11.0/bin \
        -hmmer_dir /usr/local/hmmer/bin \
        -crossmatch_dir /usr/local/phrap \
        -abblast_dir /usr/local/abblast \
        -libdir /usr/local/RepeatMasker/Libraries \
        -default_search_engine rmblast

# COPY EBbreak_modified.tar.gz /

RUN wget -q https://github.com/aokad/onebreak/archive/refs/tags/v0.1.0b8.zip && \
    unzip v0.1.0b8.zip && \
    rm v0.1.0b8.zip && \
    cd onebreak-0.1.0b8 && \
    pip3 install .
